### ISSUE TITLE
Have you really reproduced PaLM or just joking?

### ISSUE THREAD

**Issue by cherry98k** [hpcaitech/PaLM-colossalai#27]
Have you reproduced all model details? Only implementing partial model components (i.e., building the decoder as reported) should not be called reproducing PaLM or an implementation of PaLM. Have you really reproduced similar results (e.g., the sample model outputs in Appendix F)? Or you just chase the clout and assert your startup in a grandstanding manner? 

Overclaiming is a form of falsification or academic misconduct since you have not implemented or reproduced at all. 

Making fake news are very disrespectful and could mislead the entire community.🙂️

**Comment by fastalgo** [comment]
Hey, who are you? A high school student?

Why create a new anonymous account to post this?

If you want to define the rule of law, please create a new platform to replace GitHub.

GitHub is a place to share source codes and encourage open collaboration.

Many great projects are built from scratch by collaboration on GitHub.

GitHub encourages communication and ongoing review. 

Openly sharing work and feedback brings more ideas into each inner source community.

We did not overclaim anything.

We did not find any distributed PyTorch implementation before we published this.

This will help PyTorch users to build new things based on PaLM.

If you think our implementation has a bug, please let us know.

Otherwise, we will ignore your ugly and stupid nonsense.

**Comment by fastalgo** [comment]
![Screen Shot 2022-04-09 at 6 09 14 AM](https://user-images.githubusercontent.com/11185845/162538909-f7c9aefd-ca7f-48c6-984d-efecb2f65788.png)
